#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/movsx.h"
#include "data-mov/movzx.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/cmovcc.h"
#include "data-mov/leave.h"
#include "data-mov/lgdt.h"
#include "data-mov/lidt.h"
#include "data-mov/movcr.h"
#include "data-mov/movseg.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sub.h"
#include "arith/sbb.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/neg.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shld.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/cmp.h"
#include "logic/setcc.h"

#include "string/rep.h"
#include "string/stos.h"
#include "string/cmps.h"
#include "string/movs.h"

#include "misc/misc.h"

#include "special/special.h"

#include "control_transfer/call.h"
#include "control_transfer/jcc.h"
#include "control_transfer/jmp.h"
#include "control_transfer/ret.h"
#include "control_transfer/jmpnear.h"
#include "control_transfer/jmpsp.h"
#include "control_transfer/int.h"

